language: php

php:
  - "hhvm"
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"

install:
    - "composer install"

before_script:
    - "mkdir -p ./build/logs"

script:
    - "./vendor/bin/robo test"

after_success:
    - "php ./vendor/bin/coveralls -v"
